### ISSUE TITLE
editionView() returns date decremented by 1 day

### ISSUE THREAD

**Issue by wannarka** [marmelab/ng-admin#1271]
### Description

In my index.js:
```
project.editionView().fields([
         nga.field('devdate', 'date')
           .format('MM-dd-yyyy')
           .label('Development Date'),
    ]);
```
The day (dd) is decremented by 1 but the above works fine (displays the correct `devdate` response) in `project.creationView().fields`. 

### Steps to Reproduce
Plunkr: http://plnkr.co/edit/M70PbzPLBCGVZ9dollvj?p=preview

0. Set the browser to CST or any timezone less than GMT
1. Select 'Projects' in the left hand pane
2. Select 'Id' of any of the projects in the Project List; notice the 'Dev Date'
3. Now in the Edit Project form, the 'Development Date' displays decremented by 1 day
4. If user chooses to save, the 'Dev Date' will be stored in the db incorrectly.

I've tried it with and without the `.format` and `.label` with the same results. Again, creationView works just fine. And the datepicker requests with the `devdate:"2016-12-08"` so it is stored in the database accurately.

**Expected behavior:** Display 12-07-2016

**Actual behavior:** Displays 12-06-2016

**Comment by Kmaschta** [comment]
It's perhaps a timezone issue. Have you tried with different timezones, or with UTC?

**Comment by wannarka** [comment]
Yes, I checked the timezone before entering the issue and it is set correctly.

**Comment by Kmaschta** [comment]
Can you provide a Plunkr that reproduce the issue, following the [issue template](https://github.com/marmelab/ng-admin/blob/master/ISSUE_TEMPLATE.md)?

**Comment by wannarka** [comment]
As requested, Plunkr updated earlier this week.

**Comment by Kmaschta** [comment]
Your Plunkr aims the url `http://dashboard.globalvetlink.com` which is down.
You need to make it works in a standalone way.

**Comment by wannarka** [comment]
It is not down. I can access it. Route from Plunkr?

-- Scott

**Comment by wannarka** [comment]
specifically if you browse to http: http://dashboard.globalvetlink.com/projects <http://dashboard.globalvetlink.com/projects> it will return the JSON response of all the projects

**Comment by Phocea** [comment]
I also get a 404 error. This is due to a cross origin problem

> XMLHttpRequest cannot load http://dashboard.globalvetlink.com/projects?_end=30&_order=DESC&_sort=id&_start=0. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://run.plnkr.co' is therefore not allowed access.

**Comment by wannarka** [comment]
Thanks Greg. 

I knew about the 'Access-Control-Expose-Headers: x-total-count’ but didn’t realize the 'Access-Control-Allow-Origin' header should be present. It is now. 

And I’m able to reproduce the problem with the date decrementing by following the steps I posted by selecting project #66.

**Comment by Phocea** [comment]
Maybe its just me being tired, but I dont see the issue.

- Ran the plunkr
- Selected Projects / clicked on 66
- Paylod received is: `{"id":"66","projname":"Feline","owner":"Jan Johnson","description":"Today's New York Times features the story Holly the Cat, a Florida feline who traveled nearly 200 miles to get home. Ms. Johnson's cat is now famous.","devdate":"2016-12-07","stage":"Development and Beta","parked":true}`
- Development Date is displayed: 12-07-2016

So the displayed date is the same as the payload devdate (?).
If you see it as the 8th, this might well be a GMT issue .. payload is expected to be received as GMT date but local timezone is used on your browser display

**Comment by wannarka** [comment]
I agree with the first three bullets. It is the Development Date that I get 12-06-2016. If it was only a browser display issue, why would the data be changed?  If I save this, without changing anything, the next payload for “devdate" will be 12-06-2016. Also, if it was a GMT issue wouldn’t it return 12-08-2016 since I’m 6 hours behind GMT (and after 6pm but before midnight)?

Here is a screen shot:

Thanks for your assistance.

**Comment by Phocea** [comment]
Cannot see your screenshot.

On your current plunker, every date displayed, on the listview or on the individual edit views, are exactly the date received inside the response payload:

`[{"id":"66","projname":"Feline","owner":"Jan Johnson","description":"Today's New York Times features the story Holly the Cat, a Florida feline who traveled nearly 200 miles to get home. Ms. Johnson's cat is now famous.","devdate":"2016-12-07","stage":"Development and Beta","parked":true},{"id":"61","projname":"Canine","owner":"Mark Anderson","description":"The Spinone Italiano is an Italian dog breed. It was originally bred as a versatile gun dog. To this day, the breed still masters that purpose. The Spinone is a loyal, friendly and alert dog with a close lying, wiry coat.","devdate":"2016-12-08","stage":"Full Commercialization","parked":false},{"id":"18","projname":"Poultry","owner":"Mark Anderson","description":"\"Poultry\" means chickens, turkeys, domestic waterfowl, ratites, and domestic game birds, except doves and pigeons.","devdate":"2016-12-06","stage":"Development and Beta","parked":false},{"id":"4","projname":"Equine","owner":"Mark Anderson","description":"Certificate of Veterinary Inspection (CVI). All equine imported into the state of Iowa shall be accompanied by a CVI.","devdate":"2016-09-04","stage":"Feasibility & Planning","parked":true},{"id":"3","projname":"Cattle","owner":"Jan Johnson","description":"Recognized slaughter establishment means a slaughtering establishment operating under the\r\nprovisions of either the Federal Meat Inspection Act (21 U.S.C. 601 et seq.) or an equivalent state meat\r\ninspection program.","devdate":"2016-10-28","stage":"Concept Development","parked":true},{"id":"1","projname":"Swine","owner":"Jan Johnson","description":"Transitional swine means swine that have been, or have had the potential to be, exposed to feral swine.","devdate":"2016-10-30","stage":"Idea Generation","parked":false}]`

![capture d ecran 2016-12-15 20 58 48](https://cloud.githubusercontent.com/assets/724262/21240044/dc4e7776-c309-11e6-8ff5-b4fe52a0a50b.png)

**Comment by wannarka** [comment]
I edited the previous post, it is a jpeg. Hopefully you will be able to see the same thing I’m seeing.

**Comment by Phocea** [comment]
Ok for the screenshot, but what is the payload you actually receive in the browser. Check in the developper console in Chrome (CTRL+SHIFT+I).
If it is "2016-12-07", then as you can see in my screenshot , it is definitaly a regional setting problem. This is probably gthe case because when you save you are saying that it is the correct date..so probably the JSON paylod of the POST or PUT is also correct, even though displayed wrong

You may try to adapt the display date (https://github.com/marmelab/ng-admin/issues/1091) or play with the [datepicker config] (https://angular-ui.github.io/bootstrap/)

**Comment by wannarka** [comment]
I set my computer TZ to France and it works as expected. You are on correct about the payload received by the browser and it being tied to the region setting of the browsers (multiple browsers have the problem).  I’ll try to adapt the display date first.

**Comment by wannarka** [comment]
I tried adapting the display date (#1091) but it appears that the transform(dateFormatting) happens after the datepicker displays the wrong date. It leaves me with only the datepicker config.

**Comment by wannarka** [comment]
Changing the datepicker config will not address the issue either. I traced the code down and the #devDate value is "2016-12-06" before the input-group datepicker class is called. As we have already established, the devDate is correct ("2016-12-07") coming from the API in the browser and also correct in the creationView.  My best guess is it is getting changed by ng-admin-field-devDate.

**Comment by thachp** [comment]
I'm experiencing a similar problem with my datepicker field.  Beside getting the incorrect date on select, I'm also getting "Error: 10 $digest() iterations reached." The error could be my app specific.

I pinpointed the error down to these codes.  My $digest error disappeared when I commented out the $watch statement. 

            // maDateField.js LINE 30
            scope.$watch('value', function (newValue, oldValue) {
                if (newValue === oldValue) {
                    return;
                }
                
                if (!newValue) {
                    scope.rawValue = null;
                    return;
                }

                scope.rawValue = scope.value instanceof Date ? scope.value : new Date(scope.value);
            });


The solution that I came up with is to unregister $watch() instead of return inside the IF conditions. Replace the above statement with these codes.

            var $watchValue = scope.$watch('value', function (newValue, oldValue) {
                if (newValue === oldValue) {
                    $watchValue();
                }

                if (!newValue) {
                    scope.rawValue = null;
                    $watchValue();
                }

                scope.rawValue = scope.value instanceof Date ? scope.value : new Date(scope.value);
            });

@wannarka @Phocea  Can you please confirm the fixed and the merge it to master?  It is a critical bug.

**Comment by estorco** [comment]
I had the same issue and thachp's solution worked for me! 

@thachp Kudos!

**Comment by Phocea** [comment]
@thachp its a bit difficult to verify this in our timezone. In any case, could you please create a PR with your changes so the whole team can have a look ?

**Comment by wannarka** [comment]
@thachp <https://github.com/thachp> I’ll be happy to validate the fix with my app. I have the maDateField.js file updated on my server but not sure what to do next. How do I get ng-admin updated to use the change?

**Comment by matheo** [comment]
This workaround can work:
https://github.com/marmelab/ng-admin/issues/1305#issuecomment-283874657

**Comment by Kmaschta** [comment]
Okay, I just fixed an issue with the DateField.
I'm not sure that it will fix this issue about timezone, we do not manage it properly.

Let's try it again when the #1318 will be published.

**Comment by Kmaschta** [comment]
It seems fixed with the `1.0.1` as you can see on [this Plunkr](http://plnkr.co/edit/89xkfpjECnslVmhBenRB?p=preview).

**Comment by wannarka** [comment]
I tried the Plunkr linked and 1.0.1 does NOT fix the issue. In the Project List view you will see a ‘Next Review Date’. If you edit a project with a date set, it will display the previous day in any timezone where GMT minus 1-8. See my previous comments. This is easily replicated by setting your computer’s clock to a timezone in the USA.

**Comment by Kmaschta** [comment]
I am not able to reproduce, even with a timezone in the USA.
If I click on the 3rd March, the input will be filled with `2017-03-03`.
I don't find a field named `Next Review Date` either.

Can you give me more detailed infos about the bug?

**Comment by wannarka** [comment]
It would probably help to make the current code public http://plnkr.co/edit/e6xFoK?p=preview <http://plnkr.co/edit/e6xFoK?p=preview> 

In the project list, take note of the Otis and/or VL Auto Sign Up `Next Review Date`. Edit either project and you will notice the date has been decremented by one day in the field box next to `Next Review Date` when a USA timezone is used. I can do a screen capture if the link doesn’t show it.

**Comment by Kmaschta** [comment]
Okay, better!

I was able to reproduce the bug until I type `Ctrl + F5`.
I suspect a cache issue, because I'm unable again to reproduce the error.

Can you confirm?

**Comment by wannarka** [comment]
I emptied the cache and did a hard reload and I still see the problem. I also can reproduce with both Chrome and Safari.

**Comment by matheo** [comment]
Indeed, I'm GMT-5 and I see a different Date on showView and editView.

**Comment by thanhbuiea** [comment]
hi @Phocea , I'm experiencing with DateField infinite watches loop in EditionView (`Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting! Watchers fired in the last 5 iterations: `), my using version is 1.0.6. Any progress to get this problem resolved. We tried applying the fix that @thachp recommended above, and it works. Could you please let me know how to get the progress on and completed quickly?
