### ISSUE TITLE
Cannot map targetField() on creationView() and editionView() 

### ISSUE THREAD

**Issue by F3L1X79** [marmelab/ng-admin#598]
Hi again to the team, and thanks for all the efforts done on ng-admin.

On the latest branch, I have a small defect: the map() function isn't working on the creation and edition Views:

Here's my snippet:
``` js
nga.field('client', 'reference')
                    .label('Client')
                    .targetEntity(client)
                    .targetField(nga.field('email').map(function (value, entry) {
                        return entry.firstname + ' ' + entry.lastname;
                    }))
``` 

It only returns the email field - but the same code works great on the showView() and listView() (I mean, it returns firstname + lastname instead of email).

Another small thing, is that I cannot map the 'id' field on showView() and listView() - it might be part of the same problem, or not...

**Comment by F3L1X79** [comment]
Ok it looks like the map() function is now replaced by the transform() function on Edition and Creation Views, so nevermind.

**Comment by F3L1X79** [comment]
Sorry to reopen this, but I tried to change by this new snippet with the tranform() function:
nga.field('client', 'reference')
                    .label('Client')
                    .targetEntity(client)
                    .targetField(nga.field('email').transform(function (value, entry) {
                        return entry.firstname + ' ' + entry.lastname;
                    }))
``` 
But it still doesn't work with a targetField thought. It still returns email instead of firstname + lastname.

**Comment by fzaninotto** [comment]
Fixed by #659

**Comment by F3L1X79** [comment]
I'm sorry to be annoying, but it looks like it's still not working with the transform() function on the latest branch (Creation & EditionViews only)?
I may create a plunker to show you on the main demo (if one does not exist).

Thank you for all the other fixes, by the way.
