### ISSUE TITLE
remoteComplete current value not set in edititionView

### ISSUE THREAD

**Issue by jmondragon** [marmelab/ng-admin#817]
I'm trying to use a reference field where the referenced table contains quite a few records.  With the defaults set, it loads the current value into the select field, but the dropdown is limited to the first 30 records.  After reading some more I found that's the default, and it works as expected.

So my options were to raise the perPage to some really high number or use remoteComplete, so I enabled remoteComplete, and I can search for the referenced entity, but when it first loads in editionView() my current value isn't there.

Thank you

**Comment by fzaninotto** [comment]
That's already been fixed in master. Are you using the latest HEAD?

**Comment by jmondragon** [comment]
Thank you!  No, I just followed the Getting Started page and used the `npm install ng-admin --save`.  I'll clone the latest and use that (or is there a way to tell npm to use the latest HEAD)?

Thanks for a great tool, in less than I day I've got a basic admin section for my API.  It's only about 15 entities with pretty standard relationships, but it saved a ton of time and I can focus on front-end work.

**Comment by Rawgeek** [comment]
I can confirm that this is still an issue. However that might only happen in certain situations. I'll investigate and add details here. On stable 0.9.1 this wasn't as issue

**Comment by Rawgeek** [comment]
This happens if you have more than 30 entries. But because you're searching only 30(per page) when pre-populating choices if you haven't found preselected id (e.g. 999) then it's not shown so the value appears to be blank. If the entry is found when searching (e.g. id:22), then it's shown normally.
